export { default as David } from './david.jpg'
export { default as Eva } from './eva.jpg'
export { default as Jacks } from './jacks.jpg'
export { default as Jaime } from './jaime.jpg'
export { default as Kirstie } from './kirstie.jpg'
export { default as Paul } from './paul.jpg'
export { default as Sonja } from './sonja.jpg'